export {default as Homedsc} from './homedsc/homedsc'
export {default as Navbar} from './navbar/navbar'
export {default as Footer} from './footer/footer'
export {default as Textinput} from './Textinput/Textinput'
export {default as TextinputLogin} from './Textinput-login/TextinputLogin'
export {default as Propertycard} from './propertycard/Propertycard'
export{default as Predictinput} from './PredictInput/Predictinput'